### Name: Mahmoud Mohamed Omar
### Email: Mahmoudelkhashab26@gmail.com

#### Q1- construct 1d numpy array, 2d numpy array,3d numpy array.

In [6]:
import numpy as np;
oned=np.array([1,2,3,4,5,6,4,8,9,7])
twod=np.array([[1,23,5,4,5],[1,2,5,4,5,4]],dtype=object)
threed=np.array([[[1,23,5,4,5],[1,2,5,4,5,4]],[[1,23,5,4,5],[1,2,5,4,5,4]]],dtype=object)
print(oned,twod,threed)


[1 2 3 4 5 6 4 8 9 7] [list([1, 23, 5, 4, 5]) list([1, 2, 5, 4, 5, 4])] [[list([1, 23, 5, 4, 5]) list([1, 2, 5, 4, 5, 4])]
 [list([1, 23, 5, 4, 5]) list([1, 2, 5, 4, 5, 4])]]


#### Q2- Write a NumPy program to test whether any of the elements of a given array is non-zero. Hint use any()

In [12]:
lis =np.array([5,7,1,-5,2,3])
if(np.any(lis==0)):
    print("it contains a zero")

#### Q3- Write a NumPy program to create an array of 10 zeros, 10 ones, 10 fives.


In [14]:
tenzeros= np.zeros(10)
tenones = np.ones(10)
tenfives= 5*tenones
print(tenzeros,tenones,tenfives)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


#### Q4- Write a NumPy program to create an array of 10 zeros 3d


In [17]:
tenzeros3d=np.ones((10,10,10))
print(tenzeros3d)

[[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1

#### Q5- Write a NumPy program to create an array of the integers from 30 to 70.

In [19]:
lism=np.arange(30,71)
print(lism)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


#### Q6- Write a NumPy program to create a 3x3 identity matrix.


In [20]:
lisma=np.identity(3)
print(lisma)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Q7- Write a NumPy program to generate a random number between 0 and 1.

In [44]:
rn= np.random.random()
rn

0.6124790851266776

#### Q8- Write a NumPy program to create a 3X4 array using and iterate over it

In [55]:
lisy=np.random.randn(3,4)
print(lisy)
for i in range(len(lisy)):
    for j in range(len(lisy[i])):
        print(lisy[i][j],end=" ")
    print()
    

[[ 0.08453958  0.61570155 -0.65373439 -0.2703663 ]
 [-0.43073486  0.13905477 -0.32108913 -1.82482569]
 [ 0.56726956  1.10014116 -0.4745995   0.22073328]]
0.08453958210631095 0.6157015543672396 -0.653734394447701 -0.2703662975838496 
-0.43073486074062156 0.13905477051106382 -0.32108912655149086 -1.8248256861367431 
0.5672695613805707 1.1001411556228624 -0.47459950416951624 0.22073328251459978 


#### Q9- Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and
#### inside 0.

In [57]:
liso=np.zeros((10,10))
liso[0,:]=np.ones(10)
liso[:,0]=np.ones(10)
liso[9,:]=np.ones(10)
liso[:,9]=np.ones(10)
print(liso)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
